# Generated by Django 5.1.2 on 2024-11-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('ai', 'AI'), ('cloud', 'Cloud'), ('full', 'FullStack'), ('front', 'FrontEnd'), ('back', 'BackEnd'), ('analysis', 'DataAnalysis')], default='full', max_length=30),
        ),
        migrations.AddField(
            model_name='course',
            name='section1',
            field=models.TextField(default='Default text for section 1'),
        ),
        migrations.AddField(
            model_name='course',
            name='section2',
            field=models.TextField(default='Default text for section 2'),
        ),
        migrations.AddField(
            model_name='course',
            name='section3',
            field=models.TextField(default='Default text for section 3'),
        ),
        migrations.AddField(
            model_name='course',
            name='section4',
            field=models.TextField(default='Default text for section 4'),
        ),
        migrations.AddField(
            model_name='course',
            name='skills',
            field=models.TextField(default='Default skills'),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('ai', 'AI'), ('full', 'FullStack'), ('front', 'FrontEnd'), ('back', 'BackEnd'), ('analysis', 'DataAnalysis')], default='full', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='section1',
            field=models.TextField(default='Default text for section 1'),
        ),
        migrations.AddField(
            model_name='project',
            name='section2',
            field=models.TextField(default='Default text for section 2'),
        ),
        migrations.AddField(
            model_name='project',
            name='section3',
            field=models.TextField(default='Default text for section 3'),
        ),
        migrations.AddField(
            model_name='project',
            name='section4',
            field=models.TextField(default='Default text for section 4'),
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.TextField(default='Default skills'),
        ),
    ]
